pipeline{
	agent any
		tools { maven 'maven_local' jdk 'JAVA_HOME' }
		stages {
			stage('Compile Stage'){

					steps {
					/*(maven: 'maven_local'){*/
					bat """ 
					cd /d "CucumberAuto"
					'dir'
					'mvn clean install'
					"""				
					/*}*/
/*					stage('Test Stage'){

					steps {
					
					withMaven(maven: 'maven_local'){
					sh 'mvn test'
					
					}
					stage('Cucumber Reports'){

					steps {
					
					withMaven(maven: 'maven_local'){
					sh 'mvn clean install'
					}
					
					}
					}
					}
					}*/
					}
					}
					}
					}		
					
					